app:main.c check_pram.c blocksize_cur.c process_wait.c process_create.c
		gcc main.c check_pram.c blocksize_cur.c process_wait.c process_create.c -I../include -o app

main.o:
	gcc main.c -I../include -c

check_pram.o:
	gcc check_pram.c -I../include -c

blocksize_cur.o:
	gcc blocksize_cur.c -I../include -c
process_wait.o:
	gcc process_wait.c -I../include -c
process_create.o:
	gcc process_create.c -I../include -c
